@extends('layouts.master')

@section('content')

<div class="container">

<h1>Terms and Conditions</h1>

<hr>

<h3>1. ACCEPTANCE OF TERMS.</h3>

<h4>1.1 Overview.</h4>

<p>The following terms and conditions (this "TOS") govern all use by you as an Organizer (as defined below) of (a) the Suaray, LLC websites and domains (including all webpages, subdomains and subparts therein contained, the "Site"), (b) any and all services available on or through the Site or otherwise provided by Suaray, LLC ("SUARAY") for your events, and (c) all Software (as defined below) (collectively, the "Services"). The Services are owned and operated by Suaray. The Services are offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies and procedures that may be published from time to time on the Site by SUARAY. BY USING OR ACCESSING ANY PART OF THE SERVICES, YOU AGREE TO ALL OF THE TERMS AND CONDITIONS CONTAINED HEREIN AND ALL OTHER OPERATING RULES, POLICIES AND PROCEDURES THAT MAY BE PUBLISHED FROM TIME TO TIME ON THE SITE BY SUARAY. IF YOU DO NOT AGREE TO ANY OF SUCH TERMS, CONDITIONS, RULES, POLICIES OR PROCEDURES, DO NOT USE OR ACCESS THE SERVICES. THIS TOS MAY ONLY BE MODIFIED (I) ON AN EVENT BY EVENT BASIS THROUGH A WRITTEN TICKETING SERVICES AGREEMENT OR WRITTEN ADDENDUM AGREEMENT TO THIS TOS, SIGNED BY YOU AND AN AUTHORIZED OFFICER OF SUARAY, OR (II) BY SUARAY AS PROVIDED IN SECTION 1.2 BELOW.</p>

<h4>1.2 Modification.</h4>

<p>SUARAY reserves the right, at its sole discretion, to modify or replace any of the terms or conditions of this TOS at any time. It is your responsibility to check this TOS periodically for changes. Your continued use of the Services following the posting of any changes to this TOS constitutes acceptance of those changes. If any change to this TOS is not acceptable to you, your sole remedy is to cease accessing, browsing and otherwise using the Services.</p>

<h4>1.3 Language.</h4>

<p>We may translate this Terms of Service, our Privacy Policy or any other operating rules, policies and procedures that may be published from time to time on the Site into other languages for your convenience. The English language version of each of these documents is the version that governs your use of the Services and in the event of any conflict between the English language version and a translated version, the English language version will control.</p>

<h3>2. DESCRIPTION OF SUARAY.</h3>

<p>SUARAY provides a simple and quick means for registered users who are event organizers and planners ("Organizers" or "you") to collect payments with respect to the sale of tickets/registrations, merchandise and services for, and the solicitation of donations with respect to, events registered on the Site, including Service Fees (as defined below) ("Event Registration Fees"), from users who want to attend such events ("Buyers"). Organizers may visit the Site, fill out a questionnaire about their event, including pricing, location, inventory, etc., and collect Event Registration Fees online directly from Buyers. Payments are all transacted through, either (a) PayPal, Google Checkout, Authorize.net or other third party payment service methods (collectively, "Facilitated Payment Modes" or "FPM") or (b) the SUARAY payment processing gateway (the "Gateway"). For more information, please see https://www.Suaray.com. This TOS applies to you and your use of the Services as an Organizer. For the Terms of Service Agreement that applies to you and your use of the Services as a Buyer and/or other non-Organizer user or visitor, please see http://www.Suaray.com/tos/buyersandothers. For the Terms of Service Agreement that applies to you and your use of the Services as an API developer, please see http://developer.Suaray.com/terms/.</p>

<h3>3. YOUR USE OF THE SERVICES.</h3>

<h4>3.1 The Services.</h4>

<p>Suaray hereby grants you a non-exclusive, non-transferable, non-sublicensable right to access and use the Services solely for the purposes of creating an event page with respect to, and promoting, managing, tracking, and collecting Event Registration Fees for, an event that you have registered on the Site, in each case (i) in compliance with this TOS, and (ii) to the extent permitted under all applicable laws and regulations (foreign and domestic). Notwithstanding the foregoing, you shall not, and shall not permit anyone else to, directly or indirectly: (i) modify, reproduce or otherwise create derivatives of any part of the Services or Site Content (as defined below); (ii) reverse engineer, disassemble, decompile or otherwise attempt to discover the source code or structure, sequence and organization of all or any part of the Services (except that this restriction shall not apply to the limited extent restrictions on reverse engineering are prohibited by applicable local law); (iii) rent, lease, resell, distribute or use the Services for timesharing, service bureau, or commercial purposes (except for the limited commercial purpose of collecting Event Registration Fees through the Site as an Organizer in accordance with this TOS); (iv) remove or alter any proprietary notices or labels on or in the Services or Site Content; or (v) engage in any activity that interferes with or disrupts the Services.</p>

<h4>3.2 Software.</h4>

<p>If you are allowed to download or use any Software in connection with the Services, SUARAY hereby grants you a personal, non-transferable, non-sublicensable, revocable, non-exclusive license to use the Software solely for your internal use in connection with the Services, and only in accordance with this TOS and the written instructions/directions (if any) provided by SUARAY in conjunction with the Software. For purposes of this TOS, "Software" shall mean any and all software that is available on or through the Site or otherwise provided by SUARAY, including without limitation SUARAYs mobile applications (such as At The Door™, Entry Manager and the Suaray app). For clarity, the Software will be deemed a part of the "Services" hereunder.</p>

<p>The Software and the transmission of applicable data is subject to United States export controls. No Software may be downloaded or otherwise exported or re-exported in violation of U.S. export laws. Downloading or using the Software is at your sole risk. You shall also be responsible for using the Software in a manner that complies with all federal, state and local laws and the rules and regulations of all credit card companies.</p>

<p>The Software and related documentation are "commercial computer software" and "commercial computer software documentation," respectively, as such terms are used in United States Federal Acquisition Regulations Section 12.212. Any use, duplication or disclosure of the Software or such documentation by or on behalf of the U.S. Government is subject to restrictions as set forth in this TOS.</p>

<h3>4. PAYMENT METHODS.</h3>

<h4>4.1 Overview.</h4>

<p>There are two types of payment processing options Organizers may elect when using the Services: (1) "Facilitated Payment Processing" or "FPP", which consists of collecting Event Registration Fees using FPMs; and (2) "Suaray Payment Processing" or "CCP", which requires the use of the Gateway for the collection of Event Registration Fees. Depending on the payment processing option the Organizer elects when using the Services, monetary payments will be made to the Organizer directly by Buyers (via FPP) or by SUARAY (via CCP), in each case as described below.</p>

<h4>4.2 Facilitated Payment Processing.</h4>

<p>(a) Independent Relationship.</p>

<p>When using a FPM, Organizers and Buyers effect the applicable monetary payment transaction through the FPM service and are bound by the applicable terms of use governing the FPM service.</p>

<p>(b) Services Fees.</p>

<p>Organizers will collect all monies directly from Buyers under the FPP option. By registering for and using the FPP option, you agree to (i) pay SUARAY all then-applicable Suaray Service Fees and Suaray Payment Processing Fees, which are based on the number of tickets sold by you and/or the value of such tickets, and which charges are described in greater detail at www.Suaray.com/fees, and all additional on-site service fees, equipment lease charges, printed ticket fees, and any other fees and charges of any kind payable by you to SUARAY in connection with the provision of the Services (collectively, "Service Fees"), which payments shall be due and payable upon receipt of the invoice setting forth such charges; and (ii) accept the responsibility for providing refunds to Buyers at your own discretion. SUARAY will not be responsible or liable for, and Organizer hereby agrees to fully indemnify SUARAY and its affiliates for, refunds, errors in issuing refunds, or lack of refunds in connection with the use of the FPP option. Invoices are sent monthly for Service Fees incurred in the previous month.</p>

<h4>4.3 Suaray Payment Processing.</h4>


<p>(a) Gateway; Payment Process.</p>

<p>When an Organizer elects to use the Gateway for the collection of Event Registration Fees, payment processing occurs directly through SUARAY. Under the CCP option, SUARAY will collect all Event Registration Fees on behalf of the Organizer from Buyers and deduct all applicable Services Fees from the Event Registration Fees collected by SUARAY, and then pass the remainder along to the Organizer within five (5) business days after the event end date for the event to which the Event Registration Fees correspond (either by mailing a check or through an electronic funds transfer, depending on the option the Organizer has chosen through using the Site, to the address or account, respectively, that the Organizer accurately designates on the Site), provided that SUARAY reserves the right to withhold funds (i) at any time as SUARAY determines to be necessary for the processing and settlement of all refunds, disputed charges, chargebacks, customer complaints, allegations of fraud, and other discrepancies and (ii) as otherwise permitted pursuant to this TOS. SUARAY, in its sole discretion, may determine to advance a portion of Event Registration Fees to Organizer prior to the period set forth above, on such terms and conditions as SUARAY may establish from time to time. Organizer agrees that all Event Registration Fees for a given event are earned by Organizer only following conclusion of the applicable event and all Event Registration Fees ultimately due will be net of all Service Fees, refunds, disputed charges, chargebacks and other deductions, whether due to customer complaints, allegations of fraud, discrepancies related to the applicable event or otherwise. No payments shall be made to an Organizer from SUARAY with respect to any event that is cancelled. If payments have already been made by SUARAY to an Organizer for a cancelled event, such Organizer will immediately refund to SUARAY all such payments upon cancellation of such event. All sales, fees, charges, and funds are payable in U.S. Dollars, or other foreign currencies accepted by SUARAY. If Organizer elects to list Event Registration Fees in a foreign currency accepted by SUARAY, SUARAY will collect and disperse the funds in the foreign currency selected by Organizer.</p>

<p>ORGANIZER AGREES THAT ANY PAYMENT BY SUARAY OF EVENT REGISTRATION FEES PRIOR TO THE FIFTH (5TH) BUSINESS DAY AFTER THE END DATE OF THE APPLICABLE EVENT ARE MERELY ADVANCES OF AMOUNTS THAT MAY BECOME DUE TO ORGANIZER UNDER THIS TOS AND THAT SUARAY MAY DEMAND SUCH ADVANCES BACK (FROM TIME TO TIME IN ITS SOLE DISCRETION), AND ORGANIZER SHALL THEREUPON PROMPTLY (AND IN ANY CASE WITHIN FIVE (5) BUSINESS DAYS AFTER SUCH DEMAND) PAY BACK TO SUARAY SUCH ADVANCE OR ANY PORTION THEREOF DEMANDED BY SUARAY.</p>

<p>(b) Refunds.</p>

<p>(i) Under the CCP option, it is the responsibility of the Organizer to communicate its refund policy to Buyers and to issue refunds to Buyers via the Site. An Organizer shall ensure that its refund policy is consistent with the terms of this TOS and the payment and refund mechanics of the Site. The Site permits an Organizer to issue refunds to Buyers, provided the refund is issued by Organizer before ninety-six (96) hours after the end date of an event and within six (6) months after the transaction date for the underlying ticket purchase. Refunds issued following such period will not be processed through the Site, unless otherwise agreed to by SUARAY in its sole discretion. Subject to the foregoing, refunds issued by an Organizer will be processed within thirty (30) days after Organizer instructs the issuance of the refunds via the Site. All communications or disputes regarding refunds are between the Organizer and Buyer, and SUARAY will not be responsible or liable for, and Organizer hereby agrees to fully indemnify SUARAY and its affiliates for, refunds, errors in issuing refunds, or lack of refunds in connection with the use of the CCP option. (ii) Notwithstanding the foregoing, you acknowledge and agree that SUARAY shall have the right to force a refund of any or all tickets at any time for any reason or no reason, including without limitation if SUARAY receives complaints from a substantial number (as determined by SUARAY in its sole discretion) of Buyers with respect to the applicable event or another event held by Organizer, or SUARAY determines in its sole discretion that Organizer has engaged in any fraudulent activity or made any misrepresentations. Further, if one or more Buyer(s) request a refund, whether due to a cancelled event or for any other reason where SUARAY would reasonably expect to lose a chargeback, SUARAY may, in its sole discretion, issue such refund to such Buyer(s), and Organizer shall then owe the amount of such refund to SUARAY.</p>


<p>(c) Credit Card Chargebacks.</p>

<p>Under the CCP option, any credit card chargebacks initiated by a Buyer for any reason with respect to an event shall be charged back to the Organizer of such event. All communications and disputes regarding chargebacks are between the Organizer and Buyer, and SUARAY will not be responsible or liable in any way for, and Organizer hereby agrees to fully indemnify SUARAY and its affiliates for, chargebacks issued in the course of the use of the CCP option.</p>


<p>(d) No Third Party Beneficiary Rights.</p>

<p>Organizer is not a direct party to any agreement with any Payment Processing Partner or Card Scheme used to process payments in CCP nor is Organizer a third party beneficiary of any such agreement.</p>

<h4>4.4 Non-Exclusive Remedies.</h4>


<p>(a) Payment.</p>

<p>In the event that Organizer fails to pay to SUARAY any amount owed pursuant to this TOS when due, such amount shall bear interest calculated from the date due until paid in full at a rate equal to the lesser of (a) ten percent (10%) per annum, and (b) the maximum amount permitted by applicable law. In the event any amounts are owed by Organizer to SUARAY under this TOS or otherwise, SUARAY may, without limiting its other rights and remedies, (i) deduct such amounts from Organizer's outstanding balance, whether for that particular event or for any other event that Organizer lists through the Services; and/or (ii) send an invoice to Organizer for such amounts to the extent Organizer's outstanding balance is insufficient to cover these costs, in which case Organizer shall pay SUARAY such invoiced amounts within thirty (30) days after the date of the invoice. If payment for any amounts due to SUARAY hereunder are not made by Organizer when due, SUARAY reserves the right, in its sole discretion and without limiting its other rights and remedies, to terminate Organizer's registration for the Services (including any and all accounts that Organizer may have) and to cancel all other events listed by Organizer.</p>


<p>(b) Confirmation.</p>

<p>Upon receipt of a credit card authorization from each individual ticket purchase, SUARAY generates a confirmation message and issues a unique confirmation number. You agree to unconditionally accept, honor, and fulfill all ticketing commitments that have been confirmed by SUARAY through the Services, and it is your responsibility to verify the Buyer's membership status, confirmation number and/or any event restrictions prior to the subject event.</p>


<p>(c) Taxes; Withholding.</p>

<p>(i) You are solely responsible for determining which, if any, sales, use, amusement, value added, consumption, excise and other taxes, duties, levies and charges (collectively, "Taxes") apply to your use of the Services and you agree that it is your sole responsibility to, and that you will, collect, remit and report the correct amounts of all such Taxes to the applicable governmental authorities, even if SUARAY provides you with tax tools or tax calculators that assist you in doing so. SUARAY does not represent, warrant or guarantee that any tax tools or tax calculators provided to you will meet all tax requirements that may be applicable to you or that such tax tools or tax calculators will result in your collection or remittance of all applicable Taxes, which Taxes may vary based on the nature of your event, the nature of your tax status (individual, entity, business, consumer, etc.), your location, the location of your Attendees, credits and deductions for which you may qualify and other factors, and you hereby release SUARAY of any and all liability with respect to your use of the tax tools and/or tax calculators. None of such tax tools or tax calculators should be considered legal or tax advice. If you do collect Taxes on the Services, those Taxes will be treated like Event Registration Fees and SUARAY will pay such amounts to you at the same time as the underlying Event Registration Fees. If you use any tax tools or tax calculators that require you to input a tax registration number, you represent and warrant that such tax registration number is true and correct. SUARAY cannot give you legal or tax advice, so please be sure to check with your own tax advisor about any applicable Taxes. In the event that a governmental authority requires SUARAY to pay any Taxes attributable to your use of the Services, you agree to promptly and fully reimburse SUARAY for such Taxes upon demand and all costs, penalties, interest and expenses related thereto.
(ii) All Fees charged by SUARAY do not include any Taxes except to the extent that a Tax is expressly set forth in the applicable invoice or billing statement, and you agree to pay any Taxes that are imposed and payable on such Fees (other than those calculated based on SUARAY's net income) to SUARAY. If you are outside of the United States, you may be required to self-assess certain indirect Taxes on our Fees (or certain portions of our Fees) under the applicable reverse charge procedure on your indirect tax returns. To the extent you are required to self-assess, SUARAY will use reasonable efforts to note that on your invoices.</p>

<p>(iii) In addition, due to IRS regulations, if Suaray processes transactions and issues you payouts (A) for more than twenty thousand dollars ($20,000) in gross sales; and (B) for more than two hundred (200) transaction orders, in each case during a given calendar year and in the aggregate across all of your accounts, SUARAY is required to report to the IRS (i) the gross amount of transactions for which you have been paid in that calendar year and in each month of that calendar year; (ii) your name; (iii) your address; and (iv) your Tax Identification Number ("Your Tax Information"). As part of these IRS regulations, SUARAY is required to either (A) collect Your Tax Information; or (B) establish that you are a foreign person not subject to US taxes, before your accounts pass the two hundred (200) order transaction threshold in the aggregate. Once your accounts cross the two hundred (200) order transaction threshold, you agree that you will not receive any further payments from SUARAY until either (A) or (B) above are satisfied. To learn more about these IRS regulations and why we are required to do this, see our 1099-K FAQ http://help.Suaray.com/customer/en_us/portal/articles/647317</p>

<p>(iv) SUARAY reserves the right to withhold the payment of any amounts owed to you hereunder if SUARAY believes in its discretion that it is required to do so by applicable local, state, provincial, national or other law, rule, regulation, judgment or order.</p>

<h3>5. YOUR REGISTRATION OBLIGATIONS.</h3>

<p>To be a registered user of the Services as an Organizer you agree to: (a) provide true, accurate, current and complete information about yourself as prompted by the Site registration form (the "Registration Data") and (b) maintain and promptly update the Registration Data to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, not current or incomplete, or SUARAY has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, SUARAY has the right to suspend or terminate all of your accounts and refuse any and all of your current or future use of the Services (or any portion thereof). SUARAY is concerned about the safety and privacy of all its users, particularly children. For this reason, and to be consistent with the terms of use of any FPM service provider or other third party service provider, you must be at least 18 years of age, or the legal age of majority where you reside if that jurisdiction has an older age of majority, to register for an account.</p>

<h3>6. ACCOUNT, PASSWORD AND SECURITY.</h3>

<p>As part of the Site registration process, you will create a password and account. You are responsible for maintaining the confidentiality of the password and account, and are fully responsible for all activities that occur under your account, including, without limitation, all actions by sub-users registered under your account. You agree to (a) immediately notify SUARAY of any unauthorized use of your password or account or any other breach of security, and (b) ensure that you exit from your account at the end of each session. SUARAY cannot and will not be liable for any loss, damage or other liability arising from your failure to comply with this Section or from any unauthorized access to or use of your account. In the event of any dispute between two or more parties as to account ownership, you agree that SUARAY shall be the sole arbiter of such dispute in its sole discretion and that SUARAY'S decision (which may include termination or suspension of any account subject to dispute) shall be final and binding on all parties.</p>

<h3>7. CONTENT.</h3>

<h4>7.1 Site Content.</h4>

<p>You agree that all material, including without limitation information, data, software, text, design elements, graphics, images and other content (collectively, "Content"), contained in or delivered via the Services or otherwise made available by SUARAY in connection with the Services (collectively, "Site Content") is protected by copyrights, trademarks, service marks, trade secrets or other intellectual property and other proprietary rights and laws. SUARAY may own the Site Content or portions of the Site Content may be made available to SUARAY through arrangements with third parties. Except as expressly authorized by SUARAY in writing or in connection with your use of the intended functionality of the Services, you agree not to sell, license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publicly perform, publish, adapt, edit or create derivative works of any Site Content, or post any Site Content on any other web site or in a networked computer environment for any purpose. Reproducing, copying or distributing any Site Content for any other purpose is strictly prohibited without the express prior written permission of SUARAY. You shall use the Site Content only for purposes that are permitted by this TOS and any applicable laws and regulations (foreign and domestic). Any rights not expressly granted herein are reserved.</p>

<h4>7.2 Your Content.</h4>

<p>You acknowledge and agree that if you contribute, provide or make available any Content to the Site ("Your Content"), you hereby grant to SUARAY a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, transferable, sublicensable (through multiple tiers) right and license to use, reproduce, adapt, modify, distribute, translate, publish, create derivative works based on, perform, display and otherwise exploit Your Content, in whole or in part, in any media now known or hereafter developed, for any purpose whatsoever. You represent and warrant that you have all the rights, power and authority necessary to grant the foregoing license, and that all Your Content (i) does not infringe, violate, misappropriate or otherwise conflict with the rights of any third party, and (ii) complies with all applicable laws and regulations (foreign and domestic). In addition, Your Content must be accurate and truthful. SUARAY reserves the right to remove any of Your Content from the Site at any time if SUARAY believes in its sole discretion that it does not comply with this TOS. In addition, you agree that SUARAY may use your name and logo (whether or not you have made it available through the Site) for the purpose of identifying you as an existing or past customer of SUARAY both on the Site and in marketing and promotional materials. In addition, by accepting a particular Card Scheme payment type (e.g., Mastercard, Visa, American Express), you are authorizing the owner of that Card Scheme and its affiliates to use your name, address and website URL in any media from time to time.</p>

<h4>7.3 DMCA.</h4>

<p>The Digital Millennium Copyright Act of 1998 (the "DMCA") provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. copyright law. If you believe in good faith that any Content made available in connection with the Services infringes your copyright, you (or your agent) may send us a notice requesting that the Content be removed, or access to it blocked. Notices and counter-notices must meet the then-current statutory requirements imposed by the DMCA (see http://www.loc.gov/copyrightfor details). Notices and counter notices with respect to the Services should be sent to:</p>

<p>Nancy Flores  c/o C T Corporation System  818 West Seventh Street  Los Angeles, CA 90017  Attn: Suaray, LLC DMCA Agent  Telephone: 1-800-350-8850  Fax: (415) 694-7903   By Email: Suaray@wolterskluwer.com</p>

<h3>8. CONDUCT.</h3>

<h4>8.1 Certain Restrictions.</h4>

<p>You understand that you are liable for all Content, in whatever form, that you provide or otherwise make available to or through the Services, including to Buyers and other users of the Services. You agree not to use the Services to:</p>
<ul>
  <li>upload, post, email, transmit or otherwise make available any Content that is unlawful, harmful, threatening, abusive, harassing, tortuous, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable;</li>

  <li>harm minors in any way;</li>

  <li>facilitate gambling, gaming, lotteries, raffles, contests, sweepstakes and/or any other activity featuring the award of a prize other than raffles, contests or sweepstakes conducted in a manner that complies in all respects with SUARAY's Raffles, Contests and Sweepstakes Guidelines;</li>

  <li>impersonate any person or entity, including, but not limited to, an SUARAY representative or forum leader, or falsely state or otherwise misrepresent your affiliation with a person or entity;</li>

  <li>forge headers or otherwise manipulate identifiers in order to disguise the origin of any Content transmitted through the Services;</li>

  <li>upload, post, email, transmit or otherwise make available any Content that you do not have a right to make available under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements);</li>

  <li>upload, post, email, transmit or otherwise make available any Content that infringes any patent, trademark, trade secret, copyright or other intellectual property or proprietary rights of any person or entity;</li>

  <li>upload, post, email, transmit or otherwise make available any Content related to the sale or provision of goods and services other than the sale or provision of tickets and registrations to events listed on the Site and other goods and services being sold or provided in conjunction with such events;</li>

  <li>upload, post, email, transmit or otherwise make available any Content that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment or to otherwise interact with the Services in a manner not permitted by this TOS or expressly authorized by SUARAY (including through the API TOS contained at http://developer.Suaray.com/terms);</li>

  <li>interfere with or disrupt the Services or servers or networks connected to the Services, or disobey any requirements, procedures, policies or regulations of networks connected to the Services;</li>

  <li>intentionally or unintentionally violate any applicable law or regulation (foreign or domestic), including without limitation (i) regulations promulgated by the U.S. Securities and Exchange Commission, any rules of any national or other securities exchange (e.g., the New York Stock Exchange, the American Stock Exchange or the NASDAQ) and (ii) laws and regulations (foreign or domestic) regarding the sale or resale of tickets (including without limitation with respect to licensure requirements, maximums or limits on ticket prices, etc.); or</li>

  <li>stalk or otherwise harass any person or entity.</li>
</ul>
<h4>8.2 Certain Remedial Rights.</h4>

<p>You acknowledge that SUARAY does not pre-screen any Content provided or made available by you or any third party in connection with the Services, but that SUARAY and its designees shall have the right (but not the obligation) in their sole discretion to (i) monitor, alter, edit, or remove any of your Content, in whole or in part, and/or (ii) rescind and terminate your right to use the Services at any time (with or without notice) for any reason or no reason. You acknowledge and agree that SUARAY may preserve your Content and may also disclose your Content for any reason, including without limitation if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal process; (b) enforce this TOS; (c) respond to claims that any of your Content violates the rights of third parties; and/or (d) protect the rights, property, or personal safety of SUARAY, its users and/or the public. You understand that the technical processing and transmission of the Services, including Your Content, may involve (i) transmissions over various networks; and/or (ii) changes to conform and adapt to technical requirements of connecting networks or devices.</p>

<h3>9. SUB-DOMAINS.</h3>

<p>SUARAY may provide you with the right to use a sub-domain within the Site (e.g., [sub-domain prefix].Suaray.com). All such sub-domains are the sole property of SUARAY. In the event SUARAY provides you with a sub-domain, your right to use such sub-domain may be terminated by SUARAY at any time (with or without notice) for any reason or no reason.</p>
<h3>10. REFERRALS.</h3>

<p>The following terms and conditions describe the terms and conditions of SUARAY's referral programs. SUARAY reserves the absolute right to determine whether you or any other user of the Services qualifies for any of the following referral programs.</p>

<h4>10.1 Organizer Referral Program.</h4>

<p>SUARAY will pay a referral fee to persons or entities ("Organizer Referrers") that refer revenue-generating Organizers to SUARAY, subject to the following terms and conditions: (a) Prior to an Organizer's initial use of the Services, the Organizer Referrer must have contacted the Organizer and have been instrumental in getting the Organizer initially to register for and sell tickets/registrations for an event using the Services (as determined by SUARAY in its sole discretion). The referral must be properly registered with SUARAY when the Organizer initially sets up its account and the Organizer Referrer must fully comply with all instructions with respect thereto. (b) SUARAY will pay the Organizer Referrer twenty-five percent (25%) of the Suaray Service Fees (e.g., the 2.5% plus $.99 fee, which may vary based on Suaray's agreement with the applicable Organizer and does not include additional amounts such as taxes, royalties, payment processing and other Service Fees and will be net of all refunds, credit card chargebacks and all other deducted amounts) actually paid to SUARAY and retained by SUARAY for the Organizer's account during the 12-month period following the date of such Organizer's first event registration via the Services. The referral fee will be paid at the beginning of each month to the Organizer Referrer if the amount due and unpaid is five dollars ($5.00) or more. Any unpaid balances will be added to any balances due in subsequent months. (c) SUARAY reserves the right to change, modify or terminate this Organizer referral program and/or its terms at any time in its sole discretion. SUARAY reserves the right to determine what, if any, amounts are properly due Organizer Referrers hereunder in its sole discretion.</p>

<h4>10.2 Buyer Referral Software.</h4>

<p>SUARAY makes available Software via the Services that makes it possible for Organizers to offer third parties ("Buyer Referrers") a bonus in exchange for referring Buyers to their event(s) ("Referral Software"). SUARAY will make a good faith effort to provide information and instructions as necessary to use the Referral Software correctly. If you use the Referral Software in any capacity, you will comply with all such instructions. These instructions can be found at https://www.Suaray.com/publicaffiliates. For clarity, the Referral Software shall be deemed part of the "Software" and "Services" hereunder. Your use of the Referral Software is also subject to the following terms and conditions: (a) SUARAY is neither a party to any agreements (actual or implied) entered into by Organizers and Buyer Referrers, nor is it an agent, employee, partner or other representative of Organizers or Buyer Referrers. SUARAY has no responsibility for any failure or alleged failure of performance of any Organizer or Buyer Referrer to each other or to any third party. (b) SUARAY does not screen or investigate in any way the users of the Services to determine their ability or willingness to perform the obligations that may be undertaken pursuant to this Buyer referral program. Organizers and Buyer Referrers need to resolve all questions and issues between themselves. SUARAY makes no representations or warranties and gives no assurances that any Organizer or any Buyer Referrer will perform under the Buyer referrer program, including without limitation Organizers paying any money owed to Buyer Referrers. (c) SUARAY will not settle, mediate or otherwise assume responsibility for resolving disputes between Organizers and Buyer Referrers. (d) SUARAY assumes no liability arising from the use or misuse of the Referral Software, or in the event that the Referral Software fails to operate as expected, even if such failure results in the loss of data or in the misrepresentation of data necessary for the Organizers and Buyer Referrers to fulfill commitments entered into using the Referral Software.</p>

<h3>11. SPECIAL ADMONITIONS FOR INTERNATIONAL USE.</h3>

<p>Recognizing the global nature of the Internet, you agree to comply with all local rules regarding online conduct and acceptable Content. By way of illustration and not limitation, you agree to comply with all applicable laws and regulations (foreign and domestic) regarding the transmission of technical data exported from the United States or the country in which you reside.</p>

<p>In addition, the Services are subject to United States export controls. No part of the Services may be exported or re-exported into, or to a national or resident of, any country to which the U.S. has embargoed goods and/or services of the same type as the Services. By using the Services or any part thereof (including by downloading any Software), you represent and warrant that you are not located in, and you are not a national or resident of, any such country. Further, no part of the Services (including any Software) may be exported or re-exported to any person or entity appearing on the Office of Foreign Assets Control's Specially Designated Nationals and Blocked Persons List or the Bureau of Industry and Security's Denied Persons List. By using the Services or any part thereof (including by downloading any Software), you represent and warrant that you are not a person or entity or under the control of or affiliated with a person or entity that appears on any such list.</p>

<h3>12. ADDITIONAL SERVICES.</h3>

<p>SUARAY may, upon request, and for such fees as SUARAY may establish from time to time in its sole discretion, provide additional services to you beyond the functionality of the Site, including without limitation leasing ticket scanning and other equipment, providing consultants and staffers to assist you on the date of your event, and providing dedicated account management services. All such additional services, whether provided prior to, during or following your event, shall be deemed a part of the Services and subject to all the terms and conditions of this TOS. Such additional services shall be set forth in a written Addendum Agreement to this TOS, SUARAY Equipment Lease Agreement, and/or other written agreement between you and an authorized officer of SUARAY, and shall set forth the Service Fees and the other terms and conditions relating to such additional services. As a condition to the lease of any equipment, you shall enter into a separate SUARAY Equipment Lease Agreement.</p>

<h3>13. INDEMNITY.</h3>

<p>You agree to defend, indemnify and hold SUARAY, and its affiliates, and each of its and their respective officers, directors, agents, co-branders, other partners, and employees, harmless from any and all damage (whether direct, indirect, incidental, consequential or otherwise), loss, liability, cost and expense (including, without limitation, reasonable attorneys and accounting fees) resulting from any claim, demand, suit, proceeding (whether before an arbitrator, court, mediator or otherwise), or investigation made by any third party (each a "Claim") due to or arising out of: your Content; your or any of your affiliates, or any of your or your affiliates officers, directors, agents or employees, use of, contribution to or connection with the Services or violation of any rights of another; your event(s); and/or your violation of this TOS. SUARAY shall provide notice to you of any such Claim, provided that the failure or delay by SUARAY in providing such notice shall not limit your obligations hereunder. SUARAY reserves the right to assume the exclusive defense and control of any matter which is subject to indemnification under this Section, and in such case, you agree to cooperate with all reasonable requests in assisting SUARAYs defense of such matter.</p>

<h3>14. SERVICE MODIFICATIONS/SUSPENSIONS.</h3>

<p>SUARAY reserves the right at any time to, and from time to time may, modify, suspend or discontinue, temporarily or permanently, the Services (or any part thereof) for any reason or no reason with or without notice. SUARAY will not be responsible to you for a refund, in whole or part, of Service Fees for any reason, except for Service Fees (excluding the portion of Service Fees paid over to FPMs and other third party service providers used by SUARAY in connection with providing the Services) related to refunds issued to Buyers. You agree that SUARAY shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Services.</p>

<h3>15. TERMINATION.</h3>

<p>SUARAY, in its sole discretion, may terminate your password, accounts (or any part thereof) and/or your right to use the Services, and remove and discard any and all of Your Content within the Services, at any time for any reason or no reason, including, without limitation, for lack of use, failure to timely pay any fees or other monies due SUARAY, or if SUARAY believes that you have violated or acted inconsistently with the letter or spirit of this TOS. You agree that any termination of your right to use the Services may be effected without prior notice, and acknowledge and agree that SUARAY may immediately deactivate or delete your account and all related Content and files related to your account and/or bar any further access to such files or the Services. Further, you agree that SUARAY shall not be liable to you or any third-party for any termination of your right to use or otherwise access the Services. All provisions of this TOS that by their nature should survive termination of your right to use the Services shall survive (including, without limitation, all limitations on liability, releases, indemnification obligations, disclaimers of warranties, and intellectual property protections and licenses).</p>

<h3>16. LINKS.</h3>

<p>The Services may provide, or third parties may provide, links to other Internet websites or resources. Because SUARAY has no control over such websites and resources, you acknowledge and agree that SUARAY is not responsible for the availability of such websites or resources, and does not endorse and is not responsible or liable for any Content, advertising, products, services or other materials on or available from such websites or resources. You further acknowledge and agree that SUARAY shall not be responsible or liable for any damage or loss caused or alleged to be caused by or in connection with any use of or reliance on any such Content, advertising, products, services or other materials available on or through any such website or resource.</p>

<h3>17. DISCLAIMER OF WARRANTIES.</h3>

<p>THE SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. SUARAY HEREBY EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE. SUARAY MAKES NO WARRANTY THAT: (I) THE SERVICES WILL MEET YOUR REQUIREMENTS, (II) THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (III) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICES WILL BE ACCURATE OR RELIABLE, (IV) THE SERVICES THEMSELVES (OR ANY PART THEREOF) WILL MEET YOUR EXPECTATIONS, OR (V) ANY ERRORS IN THE SERVICES WILL BE CORRECTED. SUARAY IS NOT RESPONSIBLE AND SHALL HAVE NO LIABILITY FOR THE CONTENT, PRODUCTS, SERVICES, ACTIONS OR INACTIONS OF ANY USER, BUYER OR OTHER NON-ORGANIZER, ORGANIZER OR THIRD PARTY BEFORE, DURING AND/OR AFTER AN EVENT; AND SUARAY WILL HAVE NO LIABILITY WITH RESPECT TO ANY WARRANTY DISCLAIMED IN (I) THROUGH (V) ABOVE. YOU ACKNOWLEDGE THAT SUARAY HAS NO CONTROL OVER AND DOES NOT GUARANTEE THE QUALITY, SAFETY OR LEGALITY OF EVENTS ADVERTISED, THE TRUTH OR ACCURACY OF ANY USERS' (INCLUDING BUYERS', OTHER NON-ORGANIZERS' AND ORGANIZERS') CONTENT OR LISTINGS, OR THE ABILITY OF ANY USER (INCLUDING BUYERS AND ORGANIZERS) TO PERFORM, OR ACTUALLY COMPLETE A TRANSACTION. IN ADDITION, SUARAY IS NOT AFFILIATED WITH, AND HAS NO AGENCY OR EMPLOYMENT RELATIONSHIP WITH, ANY THIRD PARTY SERVICE PROVIDER USED IN CONJUNCTION WITH THE SERVICES (INCLUDING, WITHOUT LIMITATION, ANY FPM SERVICE), AND SUARAY HAS NO RESPONSIBILITY FOR, AND HEREBY DISCLAIMS ALL LIABILITY ARISING FROM, THE ACTS OR OMISSIONS OF ANY SUCH THIRD PARTY SERVICE PROVIDER. THE FOREGOING DISCLAIMERS SHALL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW. Notwithstanding the foregoing, you may report the misconduct of users, Buyers, other non-Organizers, Organizers and/or third parties in connection with the Site or any Services to SUARAY. SUARAY, in its sole discretion, may investigate the claim and take necessary action.</p>

<h3>18. LIMITATION OF LIABILITY.</h3>

<p>SUARAY, ITS PAYMENT PROCESSING PARTNERS, LICENSORS AND ANY APPLICABLE CARD SCHEMES SHALL NOT BE LIABLE UNDER ANY CIRCUMSTANCES OR UNDER ANY LEGAL THEORY, WHETHER IN TORT, CONTRACT, OR OTHERWISE, WITH RESPECT TO THE SERVICES, OR ANY OTHER SUBJECT MATTER OF THIS TOS, FOR: (I) ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF ANY OF THEM HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), (II) THE COST OF PROCUREMENT OF SUBSTITUTE SERVICES, (III) AMOUNTS IN EXCESS OF US$100.00 IN THE AGGREGATE FOR ALL CLAIMS FROM A GIVEN ORGANIZER WITH RESPECT TO THE SERVICES, OR (IV) ANY MATTERS BEYOND ANY OF THEIR REASONABLE CONTROL. SUARAY, ITS PAYMENT PROCESSING PARTNERS, LICENSORS AND ANY APPLICABLE CARD SCHEMES SHALL HAVE NO LIABILITY WITH RESPECT TO ANY OF YOUR CONTENT OR ANY CONTENT OF ANY OTHER USER OF THE SERVICES. THE FOREGOING LIMITATIONS SHALL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</p>

<h3>19. RELEASE.</h3>

<p>IN CONSIDERATION OF BEING PERMITTED TO ACCESS AND USE THE SERVICES, YOU HEREBY AGREE TO RELEASE SUARAY, AND ITS AFFILIATES, AND EACH OF ITS AND THEIR RESPECTIVE OFFICERS, DIRECTORS, AGENTS, CO-BRANDERS, OTHER PARTNERS, AND EMPLOYEES FROM ALL DAMAGES (WHETHER DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL OR OTHERWISE), LOSSES, LIABILITIES, COSTS AND EXPENSES OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, ARISING OUT OF OR IN ANY WAY CONNECTED WITH DISPUTES BETWEEN YOU AND THIRD PARTIES (INCLUDING OTHER ORGANIZERS, BUYERS, AND OTHER NON-ORGANIZERS) IN CONNECTION WITH THE SERVICES, YOUR ACCESS AND USE OF THE SERVICES, OR YOUR EVENT.</p>

<p>IN CONNECTION WITH THE FOREGOING RELEASE, YOU HEREBY WAIVE CALIFORNIA CIVIL CODE 1542 AND ANY OTHER APPLICABLE LAW OR STATUTE, WHICH SAYS, IN SUBSTANCE:</p>

<p>"A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR."</p>

<h3>20. PRIVACY.</h3>

<p>All information provided by you or collected by SUARAY in connection with the Services is governed by SUARAY's Privacy Policy, a copy of which is located at https://www.Suaray.com/privacypolicy, which is hereby incorporated by reference into this TOS. SUARAY strongly recommends that you review the Privacy Policy closely. In particular, Organizers should note that Suaray may use information it receives or collects regarding Buyers in accordance with the terms of its Privacy Policy, which may include use for marketing or promotion of other events or services that may be of interest to such Buyers. Further, any information submitted or provided by you to the Services may be publicly accessible. You should take care to protect private information or information that is important to you. SUARAY shall not be responsible for protecting any such information and is not liable for the protection of privacy of electronic mail or other information transferred through the Internet or any other network that you may use. Please be aware that if you decide to disclose personally identifiable information on the Services, this information may become public. SUARAY does not control and shall not be responsible for the acts of you or any other users (whether Organizers, Buyers, other non-Organizers or otherwise) of the Services.</p>

<h3>21. NOTICE.</h3>

<p>Notices to you may be made via either email or regular mail to the address in SUARAY's records. The Services may also provide notices of changes to this TOS or other matters by displaying notices or links to notices to you generally on the Services. Any notice from you to us shall be sent in writing to our mailing address at Suaray, LLC, 155 5th St, 7th Floor, San Francisco, CA 94103, USA, Attn: Corporate Counsel.</p>

<h3>22. TRADEMARK INFORMATION.</h3>

<p>The trademarks, service marks, and logos of SUARAY (the "SUARAY Trademarks") used and displayed in connection with the Services are registered and unregistered trademarks or service marks of SUARAY. Other company, product, and service names used in connection with the Services may be trademarks or service marks owned by third parties (the "Third Party Trademarks", and, collectively with SUARAY Trademarks, the "Trademarks"). The offering of the Services shall not be construed as granting, by implication, estoppel, or otherwise, any license or right to use any Trademark displayed in connection with the Services without the prior written consent of SUARAY specific for each such use. The Trademarks may not be used to disparage SUARAY, any third party or SUARAY's or third party's products or services, or in any manner (in SUARAY's sole judgment) that may damage any goodwill in the Trademarks. Use of any Trademarks as part of a link to or from any site is prohibited unless SUARAY approves the establishment of such a link by prior written consent specific for each such link. All goodwill generated from the use of any SUARAY Trademark shall inure to SUARAY's benefit.</p>

<h3>23. GENERAL.</h3>

<h4>23.1 Entire Agreement.</h4>

<p>This TOS constitutes the entire agreement between you and SUARAY and governs your use of the Services as an Organizer, superseding any prior or contemporaneous agreements, proposals, discussions or communications between you and SUARAY on the subject matter hereof, other than any written Ticketing Services Agreement, SUARAY Equipment Lease Agreement or Addendum Agreement between you and an authorized officer of SUARAY relating to a specified event or events. You also may be subject to additional terms and conditions that may apply when you use affiliate services, third party Content or third party software or the Services in a manner other than as governed by this TOS.</p>

<h4>23.2 Choice of Law.</h4>

<p>This TOS and the provision of the Services to you are governed by the laws of the state of California, U.S.A., as such laws are applied to agreements entered into and to be performed entirely within California by California residents.</p>

<h4>23.3 Arbitration.</h4>

<p>Any controversy or claim arising out of or relating to this TOS or the provision of the Services shall be exclusively settled by binding arbitration in accordance with the commercial arbitration rules of the Judicial Arbitration and Mediation Services, LLC Any such controversy or claim shall be arbitrated on an individual basis, and shall not be consolidated in any arbitration with any claim or controversy of any other party. The arbitration shall be conducted in San Francisco, California, and judgment on the arbitration award may be entered in any court having jurisdiction thereof. Subject to the foregoing arbitration provision, you and SUARAY agree to submit to the personal jurisdiction of the courts located within the city and county of San Francisco, California. Either you or SUARAY may seek any interim or preliminary relief from a court of competent jurisdiction in San Francisco, California, necessary to protect the rights or property of you or SUARAY (or its agents, suppliers, and subcontractors) pending the completion of arbitration.</p>

<h4>23.4 Waiver; Invalid Provisions.</h4>

<p>The failure or delay of SUARAY to exercise or enforce any right or provision of this TOS shall not constitute a waiver of such right or provision. No oral waiver, amendment or modification shall be effective under any circumstance whatsoever. If any provision of this TOS is found by an arbitrator or court of competent jurisdiction to be invalid, the parties nevertheless agree that the arbitrator or court should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of this TOS shall remain in full force and effect.</p>

<h4>23.5 Time to File Claim.</h4>

<p>You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Services or this TOS must be filed within two (2) years after such claim or cause of action arose or be forever barred.</p>

<h4>23.6 Titles.</h4>

<p>The section titles in this TOS are for convenience only and have no legal or contractual effect.</p>

<h4>23.7 Violations.</h4>
<p>Please report any violations of this TOS by email to support@Suaray.com.</p>
</br>
</br>
</br>
</br>
</br>

<h3>1. ACCEPTANCE OF TERMS.</h3>

<h4>1.1 Overview.</h4>

<p>The following terms and conditions (this "TOS") govern all use by you as a Buyer (as defined below) or other non-Organizer (as defined below) user or visitor of (a) the Suaray, LLC websites and domains (including all webpages, subdomains and subparts therein contained, the "Site"), (b) any and all services available on or through the Site or otherwise provided by Suaray, LLC ("SUARAY") in connection with events listed on the Site, and (c) all Software (as defined below) (collectively, the "Services"). The Services are owned and operated by SUARAY. The Services are offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies and procedures that may be published from time to time on the Site by SUARAY. BY USING OR ACCESSING ANY PART OF THE SERVICES, YOU AGREE TO ALL OF THE TERMS AND CONDITIONS CONTAINED HEREIN AND ALL OTHER OPERATING RULES, POLICIES AND PROCEDURES THAT MAY BE PUBLISHED FROM TIME TO TIME ON THE SITE BY SUARAY. IF YOU DO NOT AGREE TO ANY OF SUCH TERMS, CONDITIONS, RULES, POLICIES OR PROCEDURES, DO NOT USE OR ACCESS THE SERVICES.</p>

<h4>1.2 Modification.</h4>

<p>SUARAY reserves the right, at its sole discretion, to modify or replace any of the terms or conditions of this TOS at any time. It is your responsibility to check this TOS periodically for changes. Your continued use of the Services following the posting of any changes to this TOS constitutes acceptance of those changes. If any change to this TOS is not acceptable to you, your sole remedy is to cease accessing, browsing and otherwise using the Services.</p>

<h4>1.3 Language.</h4>

<p>We may translate this Terms of Service, our Privacy Policy or any other operating rules, policies and procedures that may be published from time to time on the Site into other languages for your convenience. The English language version of each of these documents is the version that governs your use of the Services and in the event of any conflict between the English language version and a translated version, the English language version will control.</p>

<h3>2. DESCRIPTION OF SUARAY.</h3>

<p>SUARAY provides a simple and quick means for registered users who are event organizers and planners ("Organizers") to collect payments with respect to the sale of tickets/registrations, merchandise and services for, and the solicitation of donations with respect to, events registered on the Site from users who want to attend such events ("Buyers" or "you"). Organizers may visit the Site, fill out a questionnaire about their event, including pricing, location, inventory, etc., and collect event registration fees online directly from Buyers. Payments are all transacted through PayPal, Google Checkout, Authorize.net or other third party payment service methods (collectively, "Facilitated Payment Modes" or "FPM") or the SUARAY payment processing gateway (the "Gateway"). For more information, please seehttps://www.Suaray.com. This TOS applies to you and your use of the Services as a Buyer and/or other non-Organizer user or visitor of the Services ("non-Organizer" or "you"). For the Terms of Service Agreement that applies to you and your use of the Services as an Organizer, please see https://www.Suaray.com/tos/organizers. For the Terms of Service Agreement that applies to you and your use of the Services as an API developer, please see http://developer.Suaray.com/terms/.</p>

<h3>3. YOUR USE OF THE SERVICES.</h3>

<h4>3.1 The Services.</h4>

<p>Suaray hereby grants you a non-exclusive, non-transferable, non-sublicensable right to access and use the Services solely for the purposes of browsing the Site, and searching for, viewing, registering for, and interacting with, an event that is registered on the Site, in each case (i) in compliance with this TOS, and (ii) to the extent permitted under all applicable laws and regulations (foreign and domestic). Notwithstanding the foregoing, you shall not, and shall not permit anyone else to, directly or indirectly: (i) modify, reproduce or otherwise create derivatives of any part of the Services or Site Content (as defined below); (ii) reverse engineer, disassemble, decompile or otherwise attempt to discover the source code or structure, sequence and organization of all or any part of the Services (except that this restriction shall not apply to the limited extent restrictions on reverse engineering are prohibited by applicable local law); (iii) rent, lease, resell, distribute or use the Services for timesharing, service bureau, or commercial purposes; (iv) remove or alter any proprietary notices or labels on or in the Services or Site Content; (v) engage in any activity that interferes with or disrupts the Services; or (vi) engage in any fraudulent activity or activity that facilitates fraud.</p>

<h4>3.2 Software.</h4>

<p>If you are allowed to download or use any Software in connection with the Services, SUARAY hereby grants you a personal, non-transferable, non-sublicensable, revocable, non-exclusive license to use the Software solely for your internal use in connection with the Services, and only in accordance with this TOS and the written instructions/directions (if any) provided by SUARAY in conjunction with the Software. For purposes of this TOS, "Software" shall mean any and all software that is available on or through the Site or otherwise provided by SUARAY, including without limitation SUARAYs mobile applications (such as At The Door™, Entry Manager and the Suaray app). For clarity, the Software will be deemed a part of the "Services" hereunder.</p>

<p>The Software and the transmission of applicable data is subject to United States export controls. No Software may be downloaded or otherwise exported or re-exported in violation of U.S. export laws. Downloading or using the Software is at your sole risk. You shall also be responsible for using the Software in a manner that complies with all federal, state and local laws and the rules and regulations of all credit card companies.</p>

<p>The Software and related documentation are "commercial computer software" and "commercial computer software documentation," respectively, as such terms are used in United States Federal Acquisition Regulations Section 12.212. Any use, duplication or disclosure of the Software or such documentation by or on behalf of the U.S. Government is subject to restrictions as set forth in this TOS.</p>

<h3>4. PAYMENT.</h3>

<h4>4.1 Independent Relationship of FPMs.</h4>

<p>When using a FPM, Organizers and Buyers effect the applicable monetary payment transaction through the FPM service, and are bound by the applicable terms of use governing the FPM service.</p>

<h4>4.2 Refunds.</h4>

<p>It is the responsibility of the Organizer to communicate its refund policy to Buyers and to issue refunds to Buyers via the Site or otherwise. If a Buyer desires to request a refund, Buyer must request the refund from the Organizer. All communications or disputes regarding refunds are between the Organizer and Buyer and SUARAY will not be responsible or liable in any way for refunds, errors in issuing refunds, or lack of refunds in connection with the Services. All communications and disputes regarding chargebacks and refunds are between the Organizer and Buyer and SUARAY will not be responsible or liable in any way for chargebacks in connection with a Buyer's use of the Services. If you are a Buyer and you wish to request a refund in connection with an event listed on the Services, you should contact the applicable Organizer directly.</p>

<h3>5. YOUR REGISTRATION OBLIGATIONS.</h3>

<p>To be a registered user of the Services, whether as a Buyer or other non-Organizer, you agree to: (a) provide true, accurate, current and complete information about yourself as prompted by the Site registration form (the "Registration Data") and (b) maintain and promptly update the Registration Data to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, not current or incomplete, or SUARAY has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, SUARAY has the right to suspend or terminate all of your accounts and refuse any and all of your current or future use of the Services (or any portion thereof). SUARAY is concerned about the safety and privacy of all its users, particularly children. For this reason, and to be consistent with the terms of use of any FPM service provider or other third party service provider, you must be at least 18 years of age, or the legal age of majority where you reside if that jurisdiction has an older age of majority, to register for an account.</p>

<h3>6. ACCOUNT, PASSWORD AND SECURITY.</h3>

<p>As part of the Site registration process, you will create a password and account. You are responsible for maintaining the confidentiality of the password and account, and are fully responsible for all activities that occur under your account, including, without limitation, all actions by sub-users registered under your account. You agree to (a) immediately notify SUARAY of any unauthorized use of your password or account or any other breach of security, and (b) ensure that you exit from your account at the end of each session. SUARAY cannot and will not be liable for any loss, damage or other liability arising from your failure to comply with this Section or from any unauthorized access to or use of your account. In the event of any dispute between two or more parties as to account ownership, you agree that SUARAY shall be the sole arbiter of such dispute in its sole discretion and that SUARAY'S decision (which may include termination or suspension of any account subject to dispute) shall be final and binding on all parties.</p>

<h3>7. CONTENT.</h3>

<h4>7.1 Site Content.</h4>

<p>You agree that all material, including without limitation information, data, software, text, design elements, graphics, images and other content (collectively, "Content"), contained in or delivered via the Services or otherwise made available by SUARAY in connection with the Services (collectively, "Site Content") is protected by copyrights, trademarks, service marks, trade secrets or other intellectual property and other proprietary rights and laws. SUARAY may own the Site Content or portions of the Site Content may be made available to SUARAY through arrangements with third parties. Except as expressly authorized by SUARAY in writing or in connection with your use of the intended functionality of the Services, you agree not to sell, license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publicly perform, publish, adapt, edit or create derivative works of any Site Content, or post any Site Content on any other web site or in a networked computer environment for any purpose. Reproducing, copying or distributing any Site Content for any other purpose is strictly prohibited without the express prior written permission of SUARAY. You shall use the Site Content only for purposes that are permitted by this TOS and any applicable laws and regulations (foreign and domestic). Any rights not expressly granted herein are reserved.</p>

<h4>7.2 Your Content.</h4>

<p>You acknowledge and agree that if you contribute, provide or make available any Content to the Site ("Your Content"), you hereby grant to SUARAY a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, transferable, sublicensable (through multiple tiers) right and license to use, reproduce, adapt, modify, distribute, translate, publish, create derivative works based on, perform, display and otherwise exploit Your Content, in whole or in part, in any media now known or hereafter developed, for any purpose whatsoever. You represent and warrant that you have all the rights, power and authority necessary to grant the foregoing license, and that all Your Content (i) does not infringe, violate, misappropriate or otherwise conflict with the rights of any third party, and (ii) complies with all applicable laws and regulations (foreign and domestic). In addition, Your Content must be accurate and truthful. SUARAY reserves the right to remove any of Your Content from the Site at any time if SUARAY believes in its sole discretion that it does not comply with this TOS. In addition, you agree that SUARAY may use your name and logo (whether or not you have made it available through the Site) for the purpose of identifying you as an existing or past customer of SUARAY both on the Site and in marketing and promotional materials.</p>

<h4>7.3 DMCA.</h4>

<p>The Digital Millennium Copyright Act of 1998 (the "DMCA") provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. copyright law. If you believe in good faith that any Content made available in connection with the Services infringes your copyright, you (or your agent) may send us a notice requesting that the Content be removed, or access to it blocked. Notices and counter-notices must meet the then-current statutory requirements imposed by the DMCA (see http://www.loc.gov/copyrightfor details). Notices and counter notices with respect to the Services should be sent to:</p>

<p>Nancy Flores  c/o C T Corporation System  818 West Seventh Street  Los Angeles, CA 90017  Attn: Suaray, LLC DMCA Agent  Telephone: 1-800-350-8850  Fax: (415) 694-7903   By Email: Suaray@wolterskluwer.com</p>

<h3>8. CONDUCT.</h3>

<h4>8.1 Certain Restrictions.</h4>

  <p>Whether you are using the Services as a Buyer or other non-Organizer, you understand that you are liable for all Content, in whatever form, that you provide or otherwise make available to or through the Services, including to Organizers, Buyers and other non-Organizers. You agree not to use the Services to:</p>
<ul>
  <li>upload, post, email, transmit or otherwise make available any Content that is unlawful, harmful, threatening, abusive, harassing, tortuous, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable;</li>
   <li>harm minors in any way;</li>
   <li>facilitate gambling, gaming, lotteries, raffles, contests, sweepstakes and/or any other activity featuring the award of a prize other than raffles, contests or sweepstakes conducted in a manner that complies in all respects with SUARAY's Raffles, Contests and Sweepstakes Guidelines;</li>
   <li>impersonate any person or entity, including, but not limited to, an SUARAY representative or forum leader, or falsely state or otherwise misrepresent your affiliation with a person or entity;</li>
   <li>forge headers or otherwise manipulate identifiers in order to disguise the origin of any Content transmitted through the Services;</li>
   <li>upload, post, email, transmit or otherwise make available any Content that you do not have a right to make available under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements);</li>
   <li>upload, post, email, transmit or otherwise make available any Content that infringes any patent, trademark, trade secret, copyright or other intellectual property or proprietary rights of any person or entity;</li>
   <li>upload, post, email, transmit or otherwise make available any Content related to the sale or provision of goods and services other than the sale or provision of tickets and registrations to events listed on the Site and other goods and services being sold or provided in conjunction with such events;</li>
   <li>upload, post, email, transmit or otherwise make available any Content that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment or to otherwise interact with the Services in a manner not permitted by this TOS or expressly authorized by SUARAY (including through the API TOS contained at http://developer.Suaray.com/terms);</li>
   <li>interfere with or disrupt the Services or servers or networks connected to the Services, or disobey any requirements, procedures, policies or regulations of networks connected to the Services;</li>
   <li>intentionally or unintentionally violate any applicable law or regulation (foreign or domestic), including without limitation (i) regulations promulgated by the U.S. Securities and Exchange Commission, any rules of any national or other securities exchange (e.g., the New York Stock Exchange, the American Stock Exchange or the NASDAQ) and (ii) laws and regulations (foreign or domestic) regarding the sale or resale of tickets (including without limitation with respect to licensure requirements, maximums or limits on ticket prices, etc.); or</li>
   <li>stalk or otherwise harass any person or entity.</li>
 </ul>

<h4>8.2 Certain Remedial Rights.</h4>

<p>Whether you are using the Services as a Buyer or other non-Organizer, you acknowledge that SUARAY does not pre-screen any Content provided or made available by you or any third party in connection with the Services, but that SUARAY and its designees shall have the right (but not the obligation) in their sole discretion to (i) monitor, alter, edit, or remove any of your Content, in whole or in part, and/or (ii) rescind and terminate your right to use the Services at any time (with or without notice) for any reason or no reason. You acknowledge and agree that SUARAY may preserve Your Content and may also disclose Your Content for any reason, including without limitation if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal process; (b) enforce this TOS; (c) respond to claims that any of Your Content violates the rights of third parties; and/or (d) protect the rights, property, or personal safety of SUARAY, its users and/or the public. You understand that the technical processing and transmission of the Services, including Your Content, may involve (i) transmissions over various networks; and/or (ii) changes to conform and adapt to technical requirements of connecting networks or devices.</p>

<h3>9. REFERRALS.</h3>

<p>The following terms and conditions describe the terms and conditions of SUARAY's referral programs. SUARAY reserves the absolute right to determine whether you or any other user of the Services qualifies for any of the following referral programs.</p>

<h4>9.1 Organizer Referral Program.</h4>

<p>SUARAY will pay a referral fee to persons or entities ("Organizer Referrers") that refer revenue-generating Organizers to SUARAY, subject to the following terms and conditions: (a) Prior to an Organizer's initial use of the Services, the Organizer Referrer must have contacted the Organizer and have been instrumental in getting the Organizer initially to register for and sell tickets/registrations for an event using the Services (as determined by SUARAY in its sole discretion). The referral must be properly registered with SUARAY when the Organizer initially sets up its account and the Organizer Referrer must fully comply with all instructions with respect thereto. (b) SUARAY will pay the Organizer Referrer twenty-five percent (25%) of the Suaray Service Fees (e.g., the 2.5% plus $.99 fee, which may vary based on Suaray's agreement with the applicable Organizer and does not include additional amounts such as taxes, royalties, payment processing and other service fees and will be net of all refunds, credit card chargebacks and all other deducted amounts) actually paid to SUARAY and retained by SUARAY for the Organizer's account during the 12-month period following the date of such Organizer's first event registration via the Services. The referral fee will be paid at the beginning of each month to the Organizer Referrer if the amount due and unpaid is five dollars ($5.00) or more. Any unpaid balances will be added to any balances due in subsequent months. (c) SUARAY reserves the right to change, modify or terminate this Organizer referral program and/or its terms at any time in its sole discretion. SUARAY reserves the right to determine what, if any, amounts are properly due Organizer Referrers hereunder in its sole discretion.</p>

<h4>9.2 Buyer Referral Software.</h4>

<p>SUARAY makes available Software via the Services that makes it possible for Organizers to offer third parties ("Buyer Referrers") a bonus in exchange for referring Buyers to their event(s) ("Referral Software"). SUARAY will make a good faith effort to provide information and instructions as necessary to use the Referral Software correctly. If you use the Referral Software in any capacity, you will comply with all such instructions. These instructions can be found at https://www.Suaray.com/publicaffiliates. For clarity, the Referral Software shall be deemed part of the "Software" and "Services" hereunder. Your use of the Referral Software is also subject to the following terms and conditions: (a) SUARAY is neither a party to any agreements (actual or implied) entered into by Organizers and Buyer Referrers, nor is it an agent, employee, partner or other representative of Organizers or Buyer Referrers. SUARAY has no responsibility for any failure or alleged failure of performance of any Organizer or Buyer Referrer to each other or to any third party. (b) SUARAY does not screen or investigate in any way the users of the Services to determine their ability or willingness to perform the obligations that may be undertaken pursuant to this Buyer referral program. Organizers and Buyer Referrers need to resolve all questions and issues between themselves. SUARAY makes no representations or warranties and gives no assurances that any Organizer or any Buyer Referrer will perform under the Buyer referrer program, including without limitation Organizers paying any money owed to Buyer Referrers. (c) SUARAY will not settle, mediate or otherwise assume responsibility for resolving disputes between Organizers and Buyer Referrers. (d) SUARAY assumes no liability arising from the use or misuse of the Referral Software, or in the event that the Referral Software fails to operate as expected, even if such failure results in the loss of data or in the misrepresentation of data necessary for the Organizers and Buyer Referrers to fulfill commitments entered into using the Referral Software.</p>

<h3>10. SPECIAL ADMONITIONS FOR INTERNATIONAL USE.</h3>

<p>Recognizing the global nature of the Internet, you agree to comply with all local rules regarding online conduct and acceptable Content. By way of illustration and not limitation, you agree to comply with all applicable laws and regulations (foreign and domestic) regarding the transmission of technical data exported from the United States or the country in which you reside.</p>

<p>In addition, the Services are subject to United States export controls. No part of the Services may be exported or re-exported into, or to a national or resident of, any country to which the U.S. has embargoed goods and/or services of the same type as the Services. By using the Services or any part thereof (including by downloading any Software), you represent and warrant that you are not located in, and you are not a national or resident of, any such country. Further, no part of the Services (including any Software) may be exported or re-exported to any person or entity appearing on the Office of Foreign Assets Control's Specially Designated Nationals and Blocked Persons List or the Bureau of Industry and Security's Denied Persons List. By using the Services or any part thereof (including by downloading any Software), you represent and warrant that you are not a person or entity or under the control of or affiliated with a person or entity that appears on any such list.</p>

<h3>11. INDEMNITY.</h3>

<p>You agree to defend, indemnify and hold SUARAY, and its affiliates, and each of its and their respective officers, directors, agents, co-branders, other partners, and employees, harmless from any and all damage (whether direct, indirect, incidental, consequential or otherwise), loss, liability, cost and expense (including, without limitation, reasonable attorneys' and accounting fees) resulting from any claim, demand, suit, proceeding (whether before an arbitrator, court, mediator or otherwise), or investigation made by any third party (each a "Claim") due to or arising out of: your Content; the events listed on the Service; your use of, contribution to or connection with the Service; your violation of this TOS; and/or your violation of any rights of another. SUARAY shall provide notice to you of any such Claim, provided that the failure or delay by SUARAY in providing such notice shall not limit your obligations hereunder. SUARAY reserves the right to assume the exclusive defense and control of any matter which is subject to indemnification under this Section, and in such case, you agree to cooperate with all reasonable requests in assisting SUARAY's defense of such matter.</p>

<h3>12. SERVICE MODIFICATIONS/SUSPENSIONS.</h3>

<p>SUARAY reserves the right at any time to, and from time to time may, modify, suspend or discontinue, temporarily or permanently, the Services (or any part thereof) for any reason or no reason with or without notice. You agree that SUARAY shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Services.</p>

<h3>13. TERMINATION.</h3>

<p>SUARAY, in its sole discretion, may terminate your password, accounts (or any part thereof) and/or your right to use the Services, and remove and discard any and all of Your Content within the Services, at any time for any reason or no reason, including, without limitation, for lack of use, failure to timely pay any fees or other monies due SUARAY, or if SUARAY believes that you have violated or acted inconsistently with the letter or spirit of this TOS. You agree that any termination of your right to use the Services may be effected without prior notice, and acknowledge and agree that SUARAY may immediately deactivate or delete your account and all related Content and files related to your account and/or bar any further access to such files or the Services. Further, you agree that SUARAY shall not be liable to you or any third-party for any termination of your right to use or otherwise access the Services. All provisions of this TOS that by their nature should survive termination of your right to use the Services shall survive (including, without limitation, all limitations on liability, releases, indemnification obligations, disclaimers of warranties, and intellectual property protections and licenses).</p>

<h3>14. LINKS.</h3>

<p>The Services may provide, or third parties may provide, links to other Internet websites or resources. Because SUARAY has no control over such websites and resources, you acknowledge and agree that SUARAY is not responsible for the availability of such websites or resources, and does not endorse and is not responsible or liable for any Content, advertising, products, services or other materials on or available from such websites or resources. You further acknowledge and agree that SUARAY shall not be responsible or liable for any damage or loss caused or alleged to be caused by or in connection with any use of or reliance on any such Content, advertising, products, services or other materials available on or through any such website or resource.</p>

<h3>15. DISCLAIMER OF WARRANTIES.</h3>

<p>THE SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. SUARAY HEREBY EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE. SUARAY MAKES NO WARRANTY THAT: (I) THE SERVICES WILL MEET YOUR REQUIREMENTS, (II) THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (III) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICES WILL BE ACCURATE OR RELIABLE, (IV) THE QUALITY, SAFETY OR LEGALITY OF ANY CONTENT, PRODUCTS, SERVICES, INFORMATION OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU, OR EVENTS ATTENDED, THROUGH THE SERVICES, OR THE SERVICES THEMSELVES (OR ANY PART THEREOF), WILL MEET YOUR EXPECTATIONS, OR (V) ANY ERRORS IN THE SERVICES WILL BE CORRECTED. SUARAY IS NOT RESPONSIBLE AND SHALL HAVE NO LIABILITY FOR THE CONTENT, PRODUCTS, SERVICES, ACTIONS OR INACTIONS OF ANY USER, BUYER OR OTHER NON-ORGANIZER, ORGANIZER OR THIRD PARTY BEFORE, DURING AND/OR AFTER AN EVENT; AND SUARAY WILL HAVE NO LIABILITY WITH RESPECT TO ANY WARRANTY DISCLAIMED IN (I) THROUGH (V) ABOVE. YOU ACKNOWLEDGE THAT SUARAY HAS NO CONTROL OVER AND DOES NOT GUARANTEE THE QUALITY, SAFETY OR LEGALITY OF EVENTS ADVERTISED, THE TRUTH OR ACCURACY OF ANY USERS' (INCLUDING BUYERS', OTHER NON-ORGANIZERS' AND ORGANIZERS') CONTENT OR LISTINGS, OR THE ABILITY OF ANY USER (INCLUDING BUYERS, OTHER NON-ORGANIZERS AND ORGANIZERS) TO PERFORM, OR ACTUALLY COMPLETE A TRANSACTION. THE FOREGOING DISCLAIMERS SHALL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW. Notwithstanding the foregoing, you may report the misconduct of users, Buyers, other non-Organizers, Organizers and/or third parties in connection with the Site or any Services to SUARAY. SUARAY, in its sole discretion, may investigate the claim and take necessary action.</p>

<h3>16. LIMITATION OF LIABILITY.</h3>

<p>SUARAY SHALL NOT BE LIABLE UNDER ANY CIRCUMSTANCES OR UNDER ANY LEGAL THEORY, WHETHER IN TORT, CONTRACT, OR OTHERWISE, WITH RESPECT TO THE SERVICES, OR ANY OTHER SUBJECT MATTER OF THIS TOS, FOR: (I) ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF SUARAY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), (II) THE COST OF PROCUREMENT OF SUBSTITUTE SERVICES, (III) AMOUNTS IN EXCESS OF US$100.00 IN THE AGGREGATE FOR ALL CLAIMS WITH RESPECT TO THE SERVICES, OR (IV) ANY MATTERS BEYOND SUARAY'S REASONABLE CONTROL. SUARAY SHALL HAVE NO LIABILITY WITH RESPECT TO ANY OF YOUR CONTENT OR ANY CONTENT OF ANY OTHER USER OF THE SERVICES. IN ADDITION, SUARAY IS NOT AFFILIATED WITH, AND HAS NO AGENCY OR EMPLOYMENT RELATIONSHIP WITH, ANY THIRD PARTY SERVICE PROVIDER USED IN CONJUNCTION WITH THE SERVICES (INCLUDING, WITHOUT LIMITATION, ANY FPM SERVICE), AND SUARAY HAS NO RESPONSIBILITY FOR, AND HEREBY DISCLAIMS ALL LIABILITY ARISING FROM, THE ACTS OR OMISSIONS OF ANY SUCH THIRD PARTY SERVICE PROVIDER. THE FOREGOING LIMITATIONS SHALL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</p>

<h3>17. RELEASE.</h3>

<p>IN CONSIDERATION OF BEING PERMITTED TO ACCESS AND USE THE SERVICES, YOU HEREBY AGREE TO RELEASE SUARAY, AND ITS AFFILIATES, AND EACH OF ITS AND THEIR RESPECTIVE OFFICERS, DIRECTORS, AGENTS, CO-BRANDERS, OTHER PARTNERS, AND EMPLOYEES FROM ALL DAMAGES (WHETHER DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL OR OTHERWISE), LOSSES, LIABILITIES, COSTS AND EXPENSES OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, ARISING OUT OF OR IN ANY WAY CONNECTED WITH DISPUTES BETWEEN YOU AND THIRD PARTIES (INCLUDING OTHER ORGANIZERS, BUYERS, AND OTHER NON-ORGANIZERS) IN CONNECTION WITH THE SERVICES, YOUR ACCESS AND USE OF THE SERVICES, OR ANY EVENTS LISTED THEREON.</p>

<p>IN CONNECTION WITH THE FOREGOING RELEASE, YOU HEREBY WAIVE CALIFORNIA CIVIL CODE 1542 AND ANY OTHER APPLICABLE LAW OR STATUTE, WHICH SAYS, IN SUBSTANCE:</p>

<p>"A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR."</p>

<h3>18. PRIVACY.</h3>

<p>All information provided by you or collected by SUARAY in connection with the Services is governed by SUARAY's Privacy Policy, a copy of which is located at https://www.Suaray.com/privacypolicy, which is hereby incorporated by reference into this TOS. SUARAY strongly recommends that you review the Privacy Policy closely. Further, any information submitted or provided by you to the Services may be publicly accessible. You should take care to protect private information or information that is important to you. SUARAY shall not be responsible for protecting any such information and is not liable for the protection of privacy of electronic mail or other information transferred through the Internet or any other network that you may use. Please be aware that if you decide to disclose personally identifiable information on the Services, this information may become public. SUARAY does not control and shall not be responsible for the acts of you or any other users (whether Organizers, Buyers, other non-Organizers or otherwise) of the Services.</p>

<h3>19. NOTICE.</h3>

<p>Notices to you may be made via either email or regular mail to the address in SUARAY's records. The Services may also provide notices of changes to this TOS or other matters by displaying notices or links to notices to you generally on the Services. Any notice from you to us shall be sent in writing to our mailing address at Suaray, LLC, 155 5th St, 7th Floor, San Francisco, CA 94103, USA, Attn: Corporate Counsel.</p>

<h3>20. TRADEMARK INFORMATION.</h3>

<p>The trademarks, service marks, and logos of SUARAY (the "SUARAY Trademarks") used and displayed in connection with the Services are registered and unregistered trademarks or service marks of SUARAY. Other company, product, and service names used in connection with the Services may be trademarks or service marks owned by third parties (the "Third Party Trademarks", and, collectively with SUARAY Trademarks, the "Trademarks"). The offering of the Services shall not be construed as granting, by implication, estoppel, or otherwise, any license or right to use any Trademark displayed in connection with the Services without the prior written consent of SUARAY specific for each such use. The Trademarks may not be used to disparage SUARAY, any third party or SUARAY's or third party's products or services, or in any manner (in SUARAY's sole judgment) that may damage any goodwill in the Trademarks. Use of any Trademarks as part of a link to or from any site is prohibited unless SUARAY approves the establishment of such a link by prior written consent specific for each such link. All goodwill generated from the use of any SUARAY Trademark shall inure to SUARAY's benefit.</p>

<h3>21. GENERAL.</h3>

<h4>21.1 Entire Agreement.</h4>

<p>This TOS (and to the extent that you are an API developer, the API TOS contained at http://developer.Suaray.com/terms/ constitutes the entire agreement between you and SUARAY and governs your use of the Services as a Buyer or other non-Organizer, superseding any prior or contemporaneous agreements, proposals, discussions or communications between you and SUARAY on the subject matter hereof. You also may be subject to additional terms and conditions that may apply when you use affiliate services, third party Content, third party software or the Services in a manner other than as governed by this TOS.</p>

<h4>21.2 Choice of Law.</h4>

<p>This TOS and the provision of the Services to you are governed by the laws of the state of California, U.S.A., as such laws are applied to agreements entered into and to be performed entirely within California by California residents.</p>

<h4>21.3 Arbitration.</h4>

<p>Any controversy or claim arising out of or relating to this TOS or the provision of the Services shall be exclusively settled by binding arbitration in accordance with the commercial arbitration rules of the Judicial Arbitration and Mediation Service, LLC Any such controversy or claim shall be arbitrated on an individual basis, and shall not be consolidated in any arbitration with any claim or controversy of any other party. The arbitration shall be conducted in San Francisco, California, and judgment on the arbitration award may be entered in any court having jurisdiction thereof. Subject to the foregoing arbitration provision, you and SUARAY agree to submit to the personal jurisdiction of the courts located within the city and county of San Francisco, California. Either you or SUARAY may seek any interim or preliminary relief from a court of competent jurisdiction in San Francisco, California, necessary to protect the rights or property of you or SUARAY (or its agents, suppliers, and subcontractors) pending the completion of arbitration.</p>

<h4>21.4 Waiver; Invalid Provisions.</h4>

<p>The failure or delay of SUARAY to exercise or enforce any right or provision of this TOS shall not constitute a waiver of such right or provision. No oral waiver, amendment or modification shall be effective under any circumstance whatsoever. If any provision of this TOS is found by an arbitrator or court of competent jurisdiction to be invalid, the parties nevertheless agree that the arbitrator or court should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of this TOS shall remain in full force and effect.</p>

<h4>21.5 Time to File Claim.</h4>

<p>You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Services or this TOS must be filed within two (2) years after such claim or cause of action arose or be forever barred.</p>

<h4>21.6 Titles.</h4>

<p>The section titles in this TOS are for convenience only and have no legal or contractual effect.</p>

<h4>21.7 Violations.</h4>

<p>Please report any violations of this TOS by email to support@Suaray.com.</p>
</div>
@stop
